language: python
sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="lua=5.4"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install --$LUA -r latest
  - source lua_install/bin/activate

script:
  - lua test.lua -v && tail -22 ./luacov.report.out && lua build.lua
